import { useState } from "react";
import { useNavigate } from "react-router";
import Button from "../components/Button";

// Import modular components
import ScoreWidget from "../components/ScoreWidget";
import TabNavigation from "../components/TabNavigation";
import TechnicalPrepPanel from "../components/TechnicalPrepPanel";
import BehavioralPrepPanel from "../components/BehavioralPrepPanel";
import SkillGapsPanel from "../components/SkillGapsPanel";
import RoadmapPanel from "../components/RoadmapPanel";

/**
 * InterviewReport Page
 * Receives AI report data objects and delegates display contents to subpanels.
 */
const InterviewReport = ({ report, onBack }) => {
  const navigate = useNavigate();
  const [activeSection, setActiveSection] = useState("overview");

  const handleBackClick = onBack || (() => navigate("/"));

  if (!report) {
    return (
      <div className="bg-zinc-900/40 backdrop-blur-xl border border-zinc-800/60 rounded-2xl p-8 text-center max-w-md mx-auto shadow-2xl">
        <h2 className="text-lg font-bold text-white">No Report Available</h2>
        <p className="text-xs text-zinc-500 mt-2">Please go back and submit details first.</p>
        <Button onClick={handleBackClick} className="mt-4 w-full" variant="secondary">
          Go Back
        </Button>
      </div>
    );
  }

  return (
    <div className="text-left space-y-8 py-4">
      
      {/* Header Info Card Panel */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center bg-zinc-900/30 border border-zinc-800/60 rounded-2xl p-6 shadow-xl gap-4">
        <div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight">
            {report.title || "Interview Readiness Report"}
          </h2>
          <p className="text-xs text-zinc-400 mt-1">
            Generated by AI coaching engine based on profile requirements.
          </p>
        </div>

        {/* Score widget */}
        <ScoreWidget score={report.matchScore} />
      </div>

      {/* Tab Navigation Menu */}
      <TabNavigation activeTab={activeSection} onTabChange={setActiveSection} />

      {/* Dynamic Content Panel rendering corresponding active state */}
      <div className="min-h-[200px]">
        
        {/* Tab 1: Overview Panel */}
        {activeSection === "overview" && (
          <div className="space-y-6">
            <div className="bg-zinc-900/40 border border-zinc-800/50 rounded-2xl p-6 shadow-xl text-left">
              <div className="border-l-2 border-purple-500 pl-4 py-1">
                <span className="text-[10px] font-bold text-purple-400 uppercase tracking-wider">Analysis Conclusion</span>
                <h4 className="text-base font-extrabold text-zinc-100 mt-1">Readiness Overview</h4>
              </div>
              <p className="text-xs sm:text-sm text-zinc-400 leading-relaxed mt-4">
                Evaluating your profile details against the requested target job roles indicates a match rating of <strong className="text-white font-bold">{report.matchScore}%</strong>.
                {report.matchScore >= 80
                  ? " You present a solid technological foundation for this position. We suggest reviewing the technical response questions and testing guides."
                  : " There are essential concepts you should acquire. Use the timeline roadmap to target development gaps."}
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-2">
              <div className="bg-zinc-900/30 border border-zinc-800/50 rounded-2xl p-5 shadow-lg text-left">
                <h5 className="text-xs font-bold text-zinc-200 uppercase tracking-wider mb-2">Key Strengths</h5>
                <p className="text-xs text-zinc-400 leading-relaxed">
                  Your background aligns with core frameworks. Focus heavily on details specified in the Technical tab.
                </p>
              </div>
              <div className="bg-zinc-900/30 border border-zinc-800/50 rounded-2xl p-5 shadow-lg text-left">
                <h5 className="text-xs font-bold text-zinc-200 uppercase tracking-wider mb-2">Behavioral Focus</h5>
                <p className="text-xs text-zinc-400 leading-relaxed">
                  Interviews look closely at team leadership and soft skills. Review the structured STAR answers.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Tab 2: Technical Questions Panel Accordion */}
        {activeSection === "technical" && (
          <TechnicalPrepPanel questions={report.technicalQuestions} />
        )}

        {/* Tab 3: Behavioral Questions Panel Accordion */}
        {activeSection === "behavioral" && (
          <BehavioralPrepPanel questions={report.behavioralQuestions} />
        )}

        {/* Tab 4: Skill Gaps Severity Tag Grid */}
        {activeSection === "gaps" && (
          <SkillGapsPanel gaps={report.skillGap} />
        )}

        {/* Tab 5: Day-wise Timeline Roadmap */}
        {activeSection === "roadmap" && (
          <RoadmapPanel plan={report.preparationPlan} />
        )}
      </div>

      {/* Action triggers */}
      <div className="flex justify-between items-center border-t border-zinc-800/80 pt-5">
        <Button variant="secondary" onClick={handleBackClick}>
          ← Start New Analysis
        </Button>
        <Button variant="secondary" onClick={() => window.print()}>
          💾 Print Report Sheet
        </Button>
      </div>

    </div>
  );
};

export default InterviewReport;
